// SPDX-License-Identifier: MIT
// Hand-written designer for the main dashboard. Builds the sidebar nav, the
// 6 content pages (Status / Alerts / Behavioural Scan / Settings / Logs / Console)
// and every static control. Code-behind file (DashboardForm.cs) handles the
// dynamic logic.
//
// This file is treated as auto-generated by the C# compiler because of the
// .Designer.cs naming convention. The `#nullable` directive below silences
// the CS8669 warnings that would otherwise fire on every `string?` field.

#nullable enable annotations

using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using WhitehatSecurity.Core;

namespace WhitehatSecurity.Ui;

public sealed partial class DashboardForm
{
    private Panel?        _sidebar;
    private Panel?        _content;
    private readonly Dictionary<string, Button> _navButtons = new();

    private void InitializeComponent()
    {
        SuspendLayout();

        // ---------------- Form ----------------
        Text          = "Whitehat Security Dashboard";
        Size          = new Size(1080, 720);
        StartPosition = FormStartPosition.CenterScreen;
        BackColor     = Theme.Bg;
        ForeColor     = Theme.TextMain;
        Font          = Theme.Body();
        MinimumSize   = new Size(960, 600);

        // ---------------- Sidebar ----------------
        _sidebar = new Panel
        {
            Dock      = DockStyle.Left,
            Width     = 200,
            BackColor = Theme.Sidebar,
            Padding   = new Padding(0, 12, 0, 12),
        };
        Controls.Add(_sidebar);

        var logo = new Label
        {
            Text      = "Whitehat Security",
            ForeColor = Theme.Accent,
            Font      = new Font("Segoe UI", 13, FontStyle.Bold),
            AutoSize  = false,
            TextAlign = ContentAlignment.MiddleCenter,
            Dock      = DockStyle.Top,
            Height    = 36,
        };
        var version = new Label
        {
            Text      = $"v{Installer.ProductVersion} Dashboard",
            ForeColor = Theme.TextDim,
            Font      = new Font("Segoe UI", 8),
            AutoSize  = false,
            TextAlign = ContentAlignment.MiddleCenter,
            Dock      = DockStyle.Top,
            Height    = 20,
        };
        _sidebar.Controls.Add(version);
        _sidebar.Controls.Add(logo);

        // Add a small spacer between header and nav buttons
        _sidebar.Controls.Add(new Panel { Dock = DockStyle.Top, Height = 16, BackColor = Theme.Sidebar });

        // ---------------- Content host ----------------
        _content = new Panel
        {
            Dock      = DockStyle.Fill,
            BackColor = Theme.Bg,
            Padding   = new Padding(20),
        };
        Controls.Add(_content);
        _content.BringToFront();

        // ---------------- Pages (built before nav buttons so we can wire them) ----------------
        _navPages["Status"]    = BuildStatusPage();
        _navPages["Alerts"]    = BuildAlertsPage();
        _navPages["AI"]        = BuildAiThreatsPage();
        _navPages["Settings"]  = BuildSettingsPage();
        _navPages["Logs"]      = BuildLogsPage();
        _navPages["Console"]   = BuildConsolePage();

        foreach (var page in _navPages.Values)
        {
            page.Dock     = DockStyle.Fill;
            page.Visible  = false;
            _content.Controls.Add(page);
        }

        // ---------------- Sidebar nav buttons ----------------
        // Buttons are added top-to-bottom; we add in reverse order so the
        // top-of-list ends up at the top of the Dock=Top stack.
        AddNavButton("Console", "[>]  Console");
        AddNavButton("Logs",    "[L]  Logs");
        AddNavButton("Settings","[C]  Settings");
        AddNavButton("AI",      "[B] Behaviour Scan");
        AddNavButton("Alerts",  "[A]  Alerts");
        AddNavButton("Status",  "[S]  Status");

        // Default page
        ShowPage("Status");

        ResumeLayout(false);
    }

    private void AddNavButton(string key, string label)
    {
        var btn = new Button
        {
            Text       = label,
            Dock       = DockStyle.Top,
            Height     = 40,
            FlatStyle  = FlatStyle.Flat,
            BackColor  = Theme.Sidebar,
            ForeColor  = Theme.TextMain,
            Font       = Theme.NavBtn(),
            TextAlign  = ContentAlignment.MiddleLeft,
            Padding    = new Padding(16, 0, 0, 0),
            Cursor     = Cursors.Hand,
            Tag        = key,
            TabIndex   = key switch
            {
                "Status" => 0,
                "Alerts" => 1,
                "AI" => 2,
                "Settings" => 3,
                "Logs" => 4,
                _ => 5,
            },
        };
        btn.FlatAppearance.BorderSize        = 0;
        btn.FlatAppearance.MouseOverBackColor = Theme.BtnHover;
        btn.Click += (_, _) => ShowPage(key);
        _sidebar!.Controls.Add(btn);
        _navButtons[key] = btn;
    }

    private void ShowPage(string key)
    {
        if (key == "Logs" && _content is not null
            && _navPages.TryGetValue("Logs", out var previous))
        {
            _content.Controls.Remove(previous);
            previous.Dispose();
            var refreshed = BuildLogsPage();
            refreshed.Dock = DockStyle.Fill;
            _navPages["Logs"] = refreshed;
            _content.Controls.Add(refreshed);
        }

        foreach (var (k, page) in _navPages)
            page.Visible = (k == key);

        // Highlight the active nav button
        foreach (var (k, btn) in _navButtons)
            btn.BackColor = (k == key) ? Theme.BtnHover : Theme.Sidebar;
        if (_navButtons.TryGetValue(key, out var activeButton)
            && activeButton.CanSelect)
            activeButton.Select();
    }

    /// <summary>
    /// Public entry point used by TrayApplicationContext to switch tabs from
    /// the system-tray context menu.
    /// </summary>
    public void OpenTab(string key)
    {
        if (_navPages.ContainsKey(key)) ShowPage(key);
    }

    // ============================================================================
    //  PAGE 1: STATUS
    // ============================================================================
    private Panel BuildStatusPage()
    {
        var page = new Panel { BackColor = Theme.Bg, AutoScroll = true };

        var title = new Label
        {
            Text      = "Live Monitoring Status",
            Font      = Theme.PageTitle(),
            ForeColor = Theme.Accent,
            AutoSize  = true,
            Location  = new Point(8, 8),
        };
        page.Controls.Add(title);

        // Stat cards — keep references to the value labels so RefreshStatusPage
        // can update them on every tick.
        var (alertCard, alertVal) = BuildStatCard("TOTAL ALERTS", "0",     Theme.Red,    new Point(8,   60));
        var (connCard,  connVal)  = BuildStatCard("CONNECTIONS",  "0",     Theme.Accent, new Point(220, 60));
        var (procCard,  procVal)  = BuildStatCard("PROCESSES",    "0",     Theme.Green,  new Point(432, 60));
        var (upCard,    upVal)    = BuildStatCard("UPTIME",       "00:00", Theme.Orange, new Point(644, 60));
        page.Controls.AddRange(new Control[] { alertCard, connCard, procCard, upCard });
        _alertCountValue = alertVal;
        _connCountValue  = connVal;
        _procCountValue  = procVal;
        _uptimeValue     = upVal;

        // Computer info card
        var info = new Panel
        {
            Location  = new Point(8, 165),
            Size      = new Size(848, 70),
            BackColor = Theme.Card,
        };
        var infoLine = new Label
        {
            Text =
                $"Computer: {Environment.MachineName}    " +
                $"User: {Environment.UserName}    " +
                // Use the program start time captured in Program.cs (not
                // DateTime.Now at form-construction time, which would lie
                // by the difference between launch and dashboard open).
                $"Started: {Program.StartedAt:HH:mm:ss}    " +
                $"Architecture: {(Environment.Is64BitProcess ? "x64" : "x86")}",
            Font      = Theme.Mono(9, FontStyle.Bold),
            ForeColor = Theme.TextMain,
            AutoSize  = false,
            AutoEllipsis = true,
            Size      = new Size(816, 22),
            Location  = new Point(16, 24),
        };
        info.Controls.Add(infoLine);
        page.Controls.Add(info);

        // Security posture row
        var postureTitle = new Label
        {
            Text      = "Security Posture",
            Font      = new Font("Segoe UI", 10, FontStyle.Bold),
            ForeColor = Theme.Accent,
            AutoSize  = true,
            Location  = new Point(8, 250),
        };
        page.Controls.Add(postureTitle);

        var postureCard = new Panel
        {
            Location  = new Point(8, 275),
            Size      = new Size(848, 80),
            BackColor = Theme.Card,
        };
        // Posture row keys are indexed in this order. RefreshPostureIndicators
        // (in DashboardForm.cs) walks them and queries SecurityPosture for the
        // live state on every status timer tick.
        var postureKeys = new[]
        {
            "Defender", "Firewall", "UAC", "RDP",
            "SecureBoot", "TPM", "HVCI", "BitLocker",
        };
        for (int i = 0; i < postureKeys.Length; i++)
        {
            int col = i % 4;
            int row = i / 4;
            var lbl = new Label
            {
                Text      = "● " + postureKeys[i] + ": Unknown",
                AccessibleName = postureKeys[i] + ": Unknown",
                ForeColor = Theme.PostureNa,    // starts gray; refresh sets the real color
                Font      = new Font("Segoe UI", 9, FontStyle.Bold),
                AutoSize  = true,
                Location  = new Point(20 + col * 200, 18 + row * 28),
            };
            postureCard.Controls.Add(lbl);
            _postureLabels[postureKeys[i]] = lbl;
        }
        page.Controls.Add(postureCard);

        // Recent alerts list
        var recentTitle = new Label
        {
            Text      = "Recent Alerts",
            Font      = new Font("Segoe UI", 10, FontStyle.Bold),
            ForeColor = Theme.Accent,
            AutoSize  = true,
            Location  = new Point(8, 370),
        };
        page.Controls.Add(recentTitle);

        _recentList.Location      = new Point(8, 395);
        _recentList.Size          = new Size(848, 250);
        _recentList.View          = View.Details;
        _recentList.FullRowSelect = true;
        _recentList.GridLines     = false;
        _recentList.BackColor     = Theme.Card;
        _recentList.ForeColor     = Theme.BodyText;
        _recentList.Font          = Theme.Mono(9);
        _recentList.HeaderStyle   = ColumnHeaderStyle.Nonclickable;
        _recentList.Columns.Add("Time",     90);
        _recentList.Columns.Add("Severity", 70);
        _recentList.Columns.Add("Category", 110);
        _recentList.Columns.Add("Title",    540);
        page.Controls.Add(_recentList);

        void LayoutStatusPage()
        {
            var width = Math.Max(620, page.ClientSize.Width - 20);
            const int gap = 12;
            var cardWidth = Math.Max(130, (width - gap * 3) / 4);
            var cards = new[] { alertCard, connCard, procCard, upCard };
            for (var i = 0; i < cards.Length; i++)
            {
                cards[i].Left = 8 + i * (cardWidth + gap);
                cards[i].Width = cardWidth;
            }
            info.Width = width;
            infoLine.Width = Math.Max(120, info.ClientSize.Width - 32);
            postureCard.Width = width;
            var labels = postureCard.Controls.OfType<Label>().ToArray();
            var columnWidth = Math.Max(
                130, (postureCard.ClientSize.Width - 40) / 4);
            for (var i = 0; i < labels.Length; i++)
                labels[i].Left = 20 + (i % 4) * columnWidth;
            _recentList.Width = width;
            _recentList.Columns[3].Width = Math.Max(
                160, _recentList.ClientSize.Width - 285);
            page.AutoScrollMinSize = new Size(0, 660);
        }
        page.Resize += (_, _) => LayoutStatusPage();
        page.HandleCreated += (_, _) => LayoutStatusPage();

        return page;
    }

    /// <summary>
    /// Builds one of the four big stat cards on the Status page. Returns the
    /// card panel and the inner Label that holds the metric so the
    /// code-behind can update it on every tick.
    /// </summary>
    private (Panel card, Label valueLabel) BuildStatCard(
        string headerText, string initialValue, Color accent, Point location)
    {
        var card = new Panel
        {
            Size      = new Size(200, 90),
            BackColor = Theme.Card,
            Location  = location,
        };
        var bar = new Panel
        {
            Dock      = DockStyle.Left,
            Width     = 4,
            BackColor = accent,
        };
        card.Controls.Add(bar);

        var header = new Label
        {
            Text      = headerText,
            Font      = Theme.CardLabel(),
            ForeColor = Theme.TextDim,
            AutoSize  = true,
            Location  = new Point(16, 14),
        };
        var value = new Label
        {
            Text      = initialValue,
            Font      = Theme.CardValue(),
            ForeColor = Theme.TextMain,
            AutoSize  = true,
            Location  = new Point(16, 32),
        };
        card.Controls.Add(header);
        card.Controls.Add(value);

        return (card, value);
    }

    // ============================================================================
    //  PAGE 2: ALERTS
    // ============================================================================
    private Panel BuildAlertsPage()
    {
        var page = new Panel { BackColor = Theme.Bg };

        var title = new Label
        {
            Text      = "Alert History",
            Font      = Theme.PageTitle(),
            ForeColor = Theme.Red,
            AutoSize  = true,
            Location  = new Point(8, 8),
        };
        page.Controls.Add(title);

        // ── Filter row (search + severity + category + export buttons) ──
        _alertSearch.Location  = new Point(8, 50);
        _alertSearch.Size      = new Size(174, 24);
        _alertSearch.Font      = Theme.Body(9);
        _alertSearch.BackColor = Theme.Card;
        _alertSearch.ForeColor = Theme.TextMain;
        _alertSearch.BorderStyle = BorderStyle.FixedSingle;
        _alertSearch.PlaceholderText = "Search alerts...";
        _alertSearch.TextChanged += OnAlertSearchChanged;
        page.Controls.Add(_alertSearch);

        _alertSeverityFilter.Location      = new Point(190, 50);
        _alertSeverityFilter.Size          = new Size(90, 24);
        _alertSeverityFilter.DropDownStyle = ComboBoxStyle.DropDownList;
        _alertSeverityFilter.BackColor     = Theme.Card;
        _alertSeverityFilter.ForeColor     = Theme.TextMain;
        _alertSeverityFilter.FlatStyle     = FlatStyle.Flat;
        _alertSeverityFilter.Font          = Theme.Body(9);
        _alertSeverityFilter.Items.AddRange(new object[] { "All", "Crit", "High", "Med", "Low", "Info" });
        _alertSeverityFilter.SelectedIndex = 0;
        _alertSeverityFilter.SelectedIndexChanged += OnAlertFilterChanged;
        page.Controls.Add(_alertSeverityFilter);

        _alertCategoryFilter.Location      = new Point(288, 50);
        _alertCategoryFilter.Size          = new Size(124, 24);
        _alertCategoryFilter.DropDownStyle = ComboBoxStyle.DropDownList;
        _alertCategoryFilter.BackColor     = Theme.Card;
        _alertCategoryFilter.ForeColor     = Theme.TextMain;
        _alertCategoryFilter.FlatStyle     = FlatStyle.Flat;
        _alertCategoryFilter.Font          = Theme.Body(9);
        _alertCategoryFilter.Items.AddRange(new object[]
        {
            "All", "Connection", "Listener", "Process", "Driver", "Service",
            "Registry", "Hosts", "Firmware", "HiddenProcess", "Memory", "BYOVD",
            "RDP", "Security",
        });
        _alertCategoryFilter.SelectedIndex = 0;
        _alertCategoryFilter.SelectedIndexChanged += OnAlertFilterChanged;
        page.Controls.Add(_alertCategoryFilter);

        // Export buttons sit on the right of the filter row
        StyleSmallButton(_btnExportCsv,  "Export CSV",  new Point(438, 49));
        _btnExportCsv.Click  += OnExportCsvClick;
        StyleSmallButton(_btnExportJson, "Export JSON", new Point(530, 49));
        _btnExportJson.Click += OnExportJsonClick;
        StyleSmallButton(_btnClearAlerts, "Clear All",  new Point(622, 49));
        _btnClearAlerts.Click += OnClearAlertsClick;
        page.Controls.Add(_btnExportCsv);
        page.Controls.Add(_btnExportJson);
        page.Controls.Add(_btnClearAlerts);

        // Right-click context menu on the alerts list. Items hidden/shown
        // dynamically based on which fields the selected alert populates.
        _alertContextMenu = new ContextMenuStrip();
        _ctxCopyRow.Click     += OnAlertCopyRowClick;
        _ctxCopyMessage.Click += OnAlertCopyMessageClick;
        _ctxIpLookup.Click    += OnIpLookupClick;
        _ctxBlockIp.Click     += OnBlockIpClick;
        _ctxKill.Click        += OnKillProcessClick;
        _ctxOpenLog.Click     += OnOpenLogClick;
        _ctxRegedit.Click     += OnRegeditClick;
        _ctxInspect.Click     += OnInspectThreatClick;
        _ctxRemediate.Click   += OnRemediateClick;
        _alertContextMenu.Items.AddRange(new ToolStripItem[]
        {
            _ctxCopyRow, _ctxCopyMessage,
            new ToolStripSeparator(),
            _ctxInspect, _ctxOpenLog, _ctxRegedit, _ctxRemediate,
            new ToolStripSeparator(),
            _ctxIpLookup, _ctxBlockIp, _ctxKill,
        });
        _alertContextMenu.Opening += OnAlertContextMenuOpening;

        // ── Alerts list ──
        // Bounds are computed in LayoutAlertsPage from the page's real size.
        // These used to be anchored Top|Bottom against a design-time height,
        // which left the list hundreds of pixels taller than the page at
        // every window size, with its last rows unreachable below the edge.
        _alertsList.Location      = new Point(8, 84);
        _alertsList.Size          = new Size(540, 400);
        _alertsList.Anchor        = AnchorStyles.Top | AnchorStyles.Left;
        _alertsList.View          = View.Details;
        _alertsList.FullRowSelect = true;
        _alertsList.GridLines     = false;
        _alertsList.BackColor     = Theme.Card;
        _alertsList.ForeColor     = Theme.BodyText;
        _alertsList.Font          = Theme.Mono(9);
        _alertsList.HeaderStyle   = ColumnHeaderStyle.Clickable;
        _alertsList.Columns.Add("Time",     85);
        _alertsList.Columns.Add("Severity", 80);
        _alertsList.Columns.Add("Category", 90);
        _alertsList.Columns.Add("Title",    140);
        _alertsList.Columns.Add("Message",  140);
        _alertsList.SelectedIndexChanged += OnAlertSelected;
        _alertsList.ColumnClick += OnAlertColumnClick;
        _alertsList.ContextMenuStrip = _alertContextMenu;
        page.Controls.Add(_alertsList);

        // Detail panel on the right
        _alertDetail.Location  = new Point(560, 84);
        _alertDetail.Size      = new Size(490, 400);
        _alertDetail.BackColor = Theme.Card;
        _alertDetail.Anchor    = AnchorStyles.Top | AnchorStyles.Left;

        _alertDetail.Padding = new Padding(16, 14, 16, 12);

        _alertDetailTitle.Text      = "Select an alert to view details";
        _alertDetailTitle.Font      = new Font("Segoe UI", 12, FontStyle.Bold);
        _alertDetailTitle.ForeColor = Theme.TextDim;
        _alertDetailTitle.Dock      = DockStyle.Top;
        _alertDetailTitle.Height    = 28;
        _alertDetailTitle.AutoEllipsis = true;

        _alertDetailBody.Dock       = DockStyle.Fill;
        _alertDetailBody.Multiline  = true;
        _alertDetailBody.ReadOnly   = true;
        // WordWrap off + Both scrollbars so a long path or message is
        // horizontally scrollable instead of being silently cut off at
        // the right edge of the panel.
        _alertDetailBody.WordWrap   = true;
        _alertDetailBody.ScrollBars = ScrollBars.Vertical;
        _alertDetailBody.BackColor  = Theme.Card;
        _alertDetailBody.ForeColor  = Theme.TextMain;
        _alertDetailBody.Font       = Theme.Mono(9);
        _alertDetailBody.BorderStyle = BorderStyle.None;
        // Action buttons. Every entry in the right-click menu has a button
        // here as well, so the actions are discoverable without knowing the
        // context menu exists. The flow panel wraps and auto-sizes, which is
        // what keeps them inside the panel at every window size.
        _alertActions.Dock          = DockStyle.Bottom;
        _alertActions.AutoSize      = true;
        _alertActions.AutoSizeMode  = AutoSizeMode.GrowAndShrink;
        _alertActions.WrapContents  = true;
        _alertActions.FlowDirection = FlowDirection.LeftToRight;
        _alertActions.Padding       = new Padding(0, 8, 0, 0);
        _alertActions.Margin        = Padding.Empty;
        _alertActions.BackColor     = Theme.Card;

        StyleActionButton(_btnInspectThreat, "Inspect Finding");
        _btnInspectThreat.Click += OnInspectThreatClick;
        StyleActionButton(_btnOpenLog, "Show File in Explorer");
        _btnOpenLog.Click += OnOpenLogClick;
        StyleActionButton(_btnRegedit, "Open in Regedit");
        _btnRegedit.Click += OnRegeditClick;
        StyleActionButton(_btnRemediate, "Remediate");
        _btnRemediate.Click += OnRemediateClick;
        StyleActionButton(_btnUndoRemediation, "Undo");
        _btnUndoRemediation.Click += OnUndoRemediationClick;
        StyleActionButton(_btnIpLookup, "IP Lookup");
        _btnIpLookup.Click += OnIpLookupClick;
        StyleActionButton(_btnBlockIp, "Block IP");
        _btnBlockIp.Click += OnBlockIpClick;
        StyleActionButton(_btnKillProcess, "Kill Process");
        _btnKillProcess.Click += OnKillProcessClick;
        StyleActionButton(_btnCopyRow, "Copy Row");
        _btnCopyRow.Click += OnAlertCopyRowClick;
        StyleActionButton(_btnCopyMessage, "Copy Message");
        _btnCopyMessage.Click += OnAlertCopyMessageClick;
        _alertActions.Controls.AddRange(new Control[]
        {
            _btnInspectThreat, _btnOpenLog, _btnRegedit,
            _btnRemediate, _btnUndoRemediation,
            _btnIpLookup, _btnBlockIp, _btnKillProcess,
            _btnCopyRow, _btnCopyMessage,
        });

        // Fill first, then the docked edges: WinForms docks from the end of
        // the collection inwards, so this order gives the body the space the
        // title and the button strip do not take.
        _alertDetail.Controls.Add(_alertDetailBody);
        _alertDetail.Controls.Add(_alertDetailTitle);
        _alertDetail.Controls.Add(_alertActions);

        page.Controls.Add(_alertDetail);

        // Hide all action buttons until an alert is selected
        ClearAlertDetail();

        void LayoutAlertsPage()
        {
            var width = Math.Max(680, page.ClientSize.Width);
            // Everything below the filter row, minus a bottom margin.
            var height = Math.Max(200, page.ClientSize.Height - 84 - 8);
            var listWidth = Math.Max(
                360, (int)((width - 28) * 0.58));
            _alertsList.SetBounds(8, 84, listWidth, height);
            var detailLeft = _alertsList.Right + 12;
            _alertDetail.SetBounds(
                detailLeft, 84,
                Math.Max(260, width - detailLeft - 8), height);
            // The title, body and button strip are docked inside
            // _alertDetail, so they follow its size on their own — no
            // per-control arithmetic to drift out of step.

            _alertsList.Columns[3].Width = Math.Max(
                110, (_alertsList.ClientSize.Width - 325) / 2);
            _alertsList.Columns[4].Width = Math.Max(
                110, _alertsList.ClientSize.Width
                    - _alertsList.Columns.Cast<ColumnHeader>()
                        .Take(4).Sum(c => c.Width) - 6);

            const int buttonWidth = 86;
            _btnClearAlerts.SetBounds(
                width - 8 - buttonWidth, 49, buttonWidth, 26);
            _btnExportJson.SetBounds(
                _btnClearAlerts.Left - 92, 49, buttonWidth, 26);
            _btnExportCsv.SetBounds(
                _btnExportJson.Left - 92, 49, buttonWidth, 26);
        }
        page.Resize += (_, _) => LayoutAlertsPage();
        page.HandleCreated += (_, _) => LayoutAlertsPage();

        return page;
    }

    /// <summary>
    /// The Security log is unreadable without elevation or membership of the
    /// local "Event Log Readers" group, and the program runs asInvoker. Say
    /// so on the checkbox rather than presenting a detection that cannot
    /// fire as if it were active.
    /// </summary>
    private static string SecurityEventsLabel() =>
        Engines.SecurityEventEngine.CanReadSecurityLog()
            ? "Security Events"
            : "Security Events  [UNAVAILABLE]";

    private static string SecurityEventsDescription() =>
        Engines.SecurityEventEngine.CanReadSecurityLog()
            ? "Remote logons, failed logins, new accounts"
            : "Needs elevation or Event Log Readers membership";

    /// <summary>
    /// Keeps a control's right (and optionally bottom) edge a fixed margin
    /// inside its parent, recomputed from the parent's real client size.
    ///
    /// Anchor does something subtly different: it preserves the gap that
    /// existed when the control was added. Every page here is built before
    /// its panel has reached its final size, so those gaps were wrong from
    /// the start and the control stayed wrong at every window size — the AI
    /// results list ended up more than twice the width of its page, and the
    /// Logs subtitle ran a full page-width past the right edge.
    /// </summary>
    private static void FitToParent(
        Control child, int rightMargin, int bottomMargin = -1)
    {
        var parent = child.Parent;
        if (parent is null) return;

        child.Anchor = AnchorStyles.Top | AnchorStyles.Left;

        void Apply()
        {
            var width = Math.Max(
                80, parent.ClientSize.Width - child.Left - rightMargin);
            var height = bottomMargin < 0
                ? child.Height
                : Math.Max(
                    60, parent.ClientSize.Height - child.Top - bottomMargin);
            child.SetBounds(child.Left, child.Top, width, height);
        }

        parent.Resize += (_, _) => Apply();
        parent.HandleCreated += (_, _) => Apply();
        Apply();
    }

    /// <summary>
    /// Action button for the alert detail strip. AutoSize means the caption
    /// always fits — the fixed 110px width these used to have clipped
    /// "Show File in Explorer" and every localized caption.
    /// </summary>
    private static void StyleActionButton(Button btn, string text)
    {
        btn.Text       = text;
        btn.AutoSize   = true;
        btn.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        btn.MinimumSize = new Size(0, 30);
        btn.Padding    = new Padding(10, 4, 10, 4);
        btn.Margin     = new Padding(0, 0, 8, 8);
        btn.FlatStyle  = FlatStyle.Flat;
        btn.BackColor  = Theme.BtnHover;
        btn.ForeColor  = Theme.TextMain;
        btn.Font       = new Font("Segoe UI", 9, FontStyle.Bold);
        btn.Cursor     = Cursors.Hand;
        btn.FlatAppearance.BorderSize = 0;
        btn.Visible    = false;
    }

    private static void StyleSmallButton(Button btn, string text, Point loc)
    {
        btn.Text       = text;
        btn.Location   = loc;
        btn.Size       = new Size(86, 26);
        btn.FlatStyle  = FlatStyle.Flat;
        btn.BackColor  = Theme.BtnHover;
        btn.ForeColor  = Theme.TextMain;
        btn.Font       = new Font("Segoe UI", 9, FontStyle.Bold);
        btn.Cursor     = Cursors.Hand;
        btn.FlatAppearance.BorderSize = 0;
    }

    // ============================================================================
    //  PAGE 3: BEHAVIOURAL SCAN — wired to HiddenProcess, Memory, BYOVD engines
    // ============================================================================
    private Panel BuildAiThreatsPage()
    {
        var page = new Panel { BackColor = Theme.Bg };

        var title = new Label
        {
            Text      = "Behavioural Scan",
            Font      = Theme.PageTitle(),
            ForeColor = Theme.Purple,
            AutoSize  = true,
            Location  = new Point(8, 8),
        };
        page.Controls.Add(title);

        var subtitle = new Label
        {
            Text      = "On-demand scan: Hidden Process · RWX Memory · BYOVD vulnerable drivers",
            Font      = Theme.Body(9),
            ForeColor = Theme.TextDim,
            AutoSize  = true,
            Location  = new Point(8, 48),
        };
        page.Controls.Add(subtitle);

        var scanBtn = new Button
        {
            Text      = "Scan Now",
            Location  = new Point(8, 76),
            Size      = new Size(140, 32),
            FlatStyle = FlatStyle.Flat,
            BackColor = Theme.Purple,
            ForeColor = Theme.TextMain,
            Font      = new Font("Segoe UI", 10, FontStyle.Bold),
            Cursor    = Cursors.Hand,
        };
        scanBtn.FlatAppearance.BorderSize = 0;
        scanBtn.Click += OnAiScanClick;
        page.Controls.Add(scanBtn);

        _aiStatusLabel.Location  = new Point(160, 84);
        _aiStatusLabel.AutoSize  = true;
        _aiStatusLabel.Font      = Theme.Body(9);
        _aiStatusLabel.ForeColor = Theme.TextDim;
        _aiStatusLabel.Text      = "Ready.";
        page.Controls.Add(_aiStatusLabel);

        _aiResultsList.Location      = new Point(8, 124);
        _aiResultsList.Size          = new Size(600, 300);
        _aiResultsList.View          = View.Details;
        _aiResultsList.FullRowSelect = true;
        _aiResultsList.GridLines     = false;
        _aiResultsList.BackColor     = Theme.Card;
        _aiResultsList.ForeColor     = Theme.BodyText;
        _aiResultsList.Font          = Theme.Mono(9);
        _aiResultsList.HeaderStyle   = ColumnHeaderStyle.Nonclickable;
        _aiResultsList.Columns.Add("Engine",   140);
        _aiResultsList.Columns.Add("Severity", 80);
        _aiResultsList.Columns.Add("Title",    250);
        _aiResultsList.Columns.Add("Message",  560);
        page.Controls.Add(_aiResultsList);
        FitToParent(_aiResultsList, rightMargin: 8, bottomMargin: 8);
        page.Resize += (_, _) =>
        {
            _aiResultsList.Columns[3].Width = Math.Max(
                180, _aiResultsList.ClientSize.Width - 470);
        };

        return page;
    }

    // ============================================================================
    //  PAGE 4: SETTINGS  (27 toggles)
    // ============================================================================
    private Panel BuildSettingsPage()
    {
        var page = new Panel
        {
            BackColor  = Theme.Bg,
            AutoScroll = true,
        };

        int y = 8;

        // -------- Header --------
        var title = new Label
        {
            Text      = "Settings",
            Font      = Theme.PageTitle(),
            ForeColor = Theme.Accent,
            AutoSize  = true,
            Location  = new Point(8, y),
        };
        page.Controls.Add(title);
        y += 36;

        var subtitle = new Label
        {
            Text      = "Toggle which findings raise notifications. Changes save automatically. Items marked [admin] trigger UAC.",
            Font      = Theme.Body(9),
            ForeColor = Theme.TextDim,
            AutoSize  = false,
            Size      = new Size(600, 36),
            Location  = new Point(8, y),
        };
        page.Controls.Add(subtitle);
        FitToParent(subtitle, rightMargin: 24);
        // The label is 36 tall; advancing by 28 put the button row 8px on
        // top of it, so the last line of the description was struck through
        // by three buttons.
        y += 40;

        // -------- Reset / Export / Import button row --------
        var btnReset  = new Button { Text = "Reset App Defaults", Location = new Point(20,  y), Size = new Size(140, 28) };
        var btnExport = new Button { Text = "Export Config",     Location = new Point(166, y), Size = new Size(120, 28) };
        var btnImport = new Button { Text = "Import Config",     Location = new Point(292, y), Size = new Size(120, 28) };
        foreach (var b in new[] { btnReset, btnExport, btnImport })
        {
            b.FlatStyle = FlatStyle.Flat;
            b.BackColor = Theme.BtnHover;
            b.ForeColor = Theme.TextMain;
            b.Font      = new Font("Segoe UI", 9, FontStyle.Bold);
            b.Cursor    = Cursors.Hand;
            b.FlatAppearance.BorderSize = 0;
            page.Controls.Add(b);
        }
        btnReset.Click  += OnResetSettingsClick;
        btnExport.Click += OnExportSettingsClick;
        btnImport.Click += OnImportSettingsClick;
        y += 38;

        // -------- Notification Categories section --------
        y = AddSectionHeader(page, "Notification Categories", y);
        var categories = new (string Key, string Label, string Desc)[]
        {
            ("Firmware",   "Firmware Integrity Changes",   "Driver/firmware file hash modifications, deletions, new files"),
            ("Driver",     "Driver Changes",               "New drivers loaded or existing drivers removed"),
            ("Service",    "New Services",                 "Newly installed or registered Windows services"),
            ("Connection", "Unknown Network Connections",  "Outbound connections from unrecognized processes (off by default — noisy)"),
            ("Process",    "Unsigned Processes",           "New processes running without a valid digital signature"),
            ("Listener",   "New Listening Ports",          "New ports opened for incoming connections"),
            ("Registry",   "Registry Startup Key Changes", "Modifications to Run/RunOnce and tamper-protection keys"),
            ("Security",   SecurityEventsLabel(),          SecurityEventsDescription()),
            ("RDP",        "Remote Desktop (RDP) Status",  "Alert when Remote Desktop is enabled"),
            ("Hosts",      "Hosts File Modifications",     "Changes to the hosts file that could redirect DNS"),
        };
        foreach (var c in categories)
            y = AddSettingCheckbox(page, c.Key, c.Label, c.Desc, _config.IsCategoryEnabled(c.Key), y);

        // The behavioural engines raise their own categories. Before v7.4.8
        // they were absent from this page, so their alerts could not be
        // turned off at all.
        y = AddSectionHeader(page, "Behavioural Detection", y + 8);
        var behavioural = new (string Key, string Label, string Desc)[]
        {
            ("HiddenProcess", "Hidden Processes",       "Processes present in the kernel list but hidden from the normal API"),
            ("Memory",        "Executable Private Memory", "Read-write-execute private memory — the fingerprint of injected code"),
            ("BYOVD",         "Vulnerable Drivers",     "Loaded drivers matching known bring-your-own-vulnerable-driver names"),
        };
        foreach (var c in behavioural)
            y = AddSettingCheckbox(page, c.Key, c.Label, c.Desc, _config.IsCategoryEnabled(c.Key), y);

        // -------- Display section --------
        y = AddSectionHeader(page, "Display & Behavior", y + 8);
        y = AddSettingCheckbox(page, "EnableToastNotifications", "Enable Toast Notifications",    "Show Windows toast/balloon notifications for alerts", _config.EnableToastNotifications, y);
        y = AddSettingCheckbox(page, "BeepOnAlert",              "Beep on Alert",                 "Play system beep when alerts occur", _config.BeepOnAlert, y);

        // -------- Firewall Profiles --------
        y = AddSectionHeader(page, "Firewall Profiles  [admin]", y + 8);
        y = AddSettingCheckbox(page, "FW_DomainProfile",  "Domain Firewall Profile",  "Enable Windows Firewall for domain networks",        _config.FW_DomainProfile,  y);
        y = AddSettingCheckbox(page, "FW_PrivateProfile", "Private Firewall Profile", "Enable Windows Firewall for private/home networks",  _config.FW_PrivateProfile, y);
        y = AddSettingCheckbox(page, "FW_PublicProfile",  "Public Firewall Profile",  "Enable Windows Firewall for public networks",        _config.FW_PublicProfile,  y);

        // -------- Firewall Block Rules --------
        y = AddSectionHeader(page, "Firewall Block Rules  [admin]", y + 8);
        y = AddSettingCheckbox(page, "FW_BlockInbound",  "Block All Inbound",   "Create a managed rule that blocks all incoming traffic until removed", _config.FW_BlockInbound,  y);
        y = AddSettingCheckbox(page, "FW_BlockPing",     "Block ICMP Ping",     "Block incoming ping requests",                              _config.FW_BlockPing,     y);
        y = AddSettingCheckbox(page, "FW_BlockLAN",      "Block LAN Traffic",   "Block all local network traffic",                           _config.FW_BlockLAN,      y);
        y = AddSettingCheckbox(page, "FW_BlockDevices",  "Block Device Discovery", "Block SMB / NetBIOS / LLMNR / mDNS",                     _config.FW_BlockDevices,  y);

        // -------- Host-Based Protection --------
        y = AddSectionHeader(page, "Host-Based Protection  [admin]", y + 8);
        y = AddSettingCheckbox(page, "PF_BlockTrackers",  "Block Trackers",     "Block known tracking domains via hosts file",          _config.PF_BlockTrackers,  y);
        y = AddSettingCheckbox(page, "PF_BlockMalware",   "Block Malware",      "Block known malware domains via hosts file",            _config.PF_BlockMalware,   y);
        y = AddSettingCheckbox(page, "PF_BlockTelemetry", "Block Telemetry",    "Block Windows and third-party telemetry domains",       _config.PF_BlockTelemetry, y);

        // -------- DNS section --------
        y = AddSectionHeader(page, "DNS & Secure DNS  [admin]", y + 8);
        var dnsLabel = new Label
        {
            Text      = "DNS Provider:",
            Font      = new Font("Segoe UI", 10, FontStyle.Bold),
            ForeColor = Theme.TextMain,
            AutoSize  = true,
            Location  = new Point(20, y + 6),
        };
        page.Controls.Add(dnsLabel);
        var dnsCombo = new ComboBox
        {
            Location      = new Point(160, y + 4),
            Size          = new Size(220, 24),
            DropDownStyle = ComboBoxStyle.DropDownList,
            BackColor     = Theme.Card,
            ForeColor     = Theme.TextMain,
            FlatStyle     = FlatStyle.Flat,
            Font          = Theme.Body(9),
        };
        dnsCombo.Items.AddRange(
            DnsConfiguration.ProviderNames.ToArray<object>());
        dnsCombo.SelectedItem = _config.DNS_Provider;
        dnsCombo.SelectedIndexChanged += OnDnsProviderChanged;
        page.Controls.Add(dnsCombo);
        _dnsProviderCombo = dnsCombo;
        var dnsApply = new Button
        {
            Text      = "Apply / Repair",
            Location  = new Point(392, y + 3),
            Size      = new Size(126, 28),
            FlatStyle = FlatStyle.Flat,
            BackColor = Theme.AccentDim,
            ForeColor = Theme.TextMain,
            Font      = Theme.Body(9, FontStyle.Bold),
            Cursor    = Cursors.Hand,
        };
        dnsApply.FlatAppearance.BorderSize = 0;
        dnsApply.Click += OnApplyDnsClick;
        page.Controls.Add(dnsApply);
        _dnsApplyButton = dnsApply;

        var dnsStatus = new Label
        {
            Text      = "Ready to apply and verify",
            Location  = new Point(160, y + 35),
            AutoSize  = true,
            Font      = Theme.Body(8.5f),
            ForeColor = Theme.TextDim,
        };
        page.Controls.Add(dnsStatus);
        _dnsStatusLabel = dnsStatus;
        y += 58;

#if STORE_BUILD
        var dohNotice = new Label
        {
            Text = "Manage DNS encryption in Windows network settings for the selected adapter.",
            Location = new Point(20, y),
            Size = new Size(800, 34),
            Font = Theme.Body(9),
            ForeColor = Theme.TextDim,
            Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right,
        };
        page.Controls.Add(dohNotice);
        y += 38;
        var windowsDnsSettings = new Button
        {
            Text = "Open Windows Network Settings",
            Location = new Point(20, y),
            Size = new Size(290, 32),
            FlatStyle = FlatStyle.Flat,
            BackColor = Theme.AccentDim,
            ForeColor = Theme.TextMain,
            Font = Theme.Body(9),
            Cursor = Cursors.Hand,
        };
        windowsDnsSettings.FlatAppearance.BorderSize = 0;
        windowsDnsSettings.Click += (_, _) =>
        {
            try
            {
                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(
                    "ms-settings:network-status") { UseShellExecute = true });
            }
            catch (Exception ex)
            {
                _logger.Error($"Windows network settings: {ex.Message}");
                MessageBox.Show(this, "Open Windows Settings > Network & internet to " +
                    "manage DNS encryption for your adapter.", "Windows Network Settings",
                    MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        };
        page.Controls.Add(windowsDnsSettings);
        y += 40;
#else
        y = AddSettingCheckbox(page, "DNS_DoH", "Enable DNS over HTTPS", "Encrypt DNS queries (requires compatible provider)", _config.DNS_DoH, y);
#endif
        ApplyDnsControlState();

        // Final padding so the last setting isn't flush with the bottom edge
        page.Controls.Add(new Panel { Location = new Point(0, y + 24), Size = new Size(1, 1) });
        page.Resize += (_, _) =>
        {
            if (page.ClientSize.Width < 360) return;
            foreach (Control control in page.Controls)
            {
                if (control is Panel panel && panel.Width > 700)
                    panel.Width = Math.Max(
                        280, page.ClientSize.Width - panel.Left - 16);
            }
            subtitle.Width = Math.Max(280, page.ClientSize.Width - 20);
            page.AutoScrollMinSize = new Size(0, y + 36);
        };

        return page;
    }

    private int AddSectionHeader(Panel page, string text, int y)
    {
        var sep = new Panel
        {
            Location  = new Point(8, y + 4),
            Size      = new Size(840, 1),
            BackColor = Theme.Separator,
        };
        page.Controls.Add(sep);

        var lbl = new Label
        {
            Text      = text,
            Font      = Theme.SectionTitle(),
            ForeColor = Theme.AccentBlue,
            AutoSize  = true,
            UseMnemonic = false,
            Location  = new Point(8, y + 10),
        };
        page.Controls.Add(lbl);
        return y + 38;
    }

    private int AddSettingCheckbox(Panel page, string key, string label, string desc, bool initial, int y)
    {
        var card = new Panel
        {
            Location  = new Point(20, y),
            Size      = new Size(820, 46),
            BackColor = Theme.Card,
        };
        card.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;

        var cb = new CheckBox
        {
            Text      = label,
            Location  = new Point(14, 6),
            Size      = new Size(420, 20),
            Font      = new Font("Segoe UI", 10, FontStyle.Bold),
            ForeColor = Theme.TextMain,
            BackColor = Theme.Card,
            Tag       = key,
            Checked   = initial,
        };
        cb.CheckedChanged += OnSettingsCheckChanged;
        card.Controls.Add(cb);
        _settingsCheckboxes[key] = cb;

        var d = new Label
        {
            Text      = desc,
            Location  = new Point(34, 26),
            Size      = new Size(770, 16),
            Font      = Theme.Body(8),
            ForeColor = Theme.TextDim,
            BackColor = Theme.Card,
        };
        d.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        card.Controls.Add(d);

        page.Controls.Add(card);
        return y + 52;
    }

    // ============================================================================
    //  PAGE 5: LOGS
    // ============================================================================
    private Panel BuildLogsPage()
    {
        var page = new Panel { BackColor = Theme.Bg, AutoScroll = true };
        // Keep all log-page content inside one docked body. Directly placing
        // wide cards on an AutoScroll panel makes WinForms cache their
        // pre-layout width and can leave a phantom horizontal scrollbar.
        var body = new Panel
        {
            BackColor = Theme.Bg,
            Dock = DockStyle.Top,
            Size = new Size(864, 110),
        };
        page.Controls.Add(body);

        var title = new Label
        {
            Text      = "Log Files",
            Font      = Theme.PageTitle(),
            ForeColor = Theme.Accent,
            AutoSize  = true,
            Location  = new Point(8, 8),
        };
        body.Controls.Add(title);

        var subtitle = new Label
        {
            Text      = "Every log file under the data directory. Click any card to open in Notepad. Files older than 30 days are pruned automatically at startup.",
            Font      = Theme.Body(9),
            ForeColor = Theme.TextDim,
            AutoSize  = false,
            Size      = new Size(600, 36),
            Location  = new Point(8, 44),
        };
        body.Controls.Add(subtitle);
        FitToParent(subtitle, rightMargin: 24);

        var logsDir = Paths.LogsDir;
        var files = new List<FileInfo>();
        try
        {
            if (Directory.Exists(logsDir))
            {
                foreach (var f in Directory.EnumerateFiles(logsDir, "*.log"))
                    files.Add(new FileInfo(f));
            }
        }
        catch { /* ignored */ }
        // Newest first so today's logs are at the top
        files.Sort((a, b) => b.LastWriteTime.CompareTo(a.LastWriteTime));

        if (files.Count == 0)
        {
            var empty = new Label
            {
                Text      = "(no log files yet — they appear after the first scan tick)",
                Font      = Theme.Body(9),
                ForeColor = Theme.TextDim,
                AutoSize  = true,
                Location  = new Point(8, 80),
            };
            body.Controls.Add(empty);
            return page;
        }

        int y = 80;
        foreach (var fi in files)
        {
            var card = new Panel
            {
                Location  = new Point(8, y),
                Size      = new Size(840, 56),
                BackColor = Theme.Card,
                Cursor    = Cursors.Hand,
                Tag       = fi.FullName,
                Anchor    = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right,
            };
            card.Click += OnOpenFileClick;

            var t = new Label
            {
                Text      = fi.Name,
                Font      = new Font("Segoe UI", 11, FontStyle.Bold),
                ForeColor = Theme.AccentBlue,
                AutoSize  = true,
                Location  = new Point(16, 8),
            };
            t.Click += OnOpenFileClick;
            t.Tag    = card.Tag;
            card.Controls.Add(t);

            var d = new Label
            {
                Text      = $"{FormatFileSize(fi.Length)}   ·   {fi.LastWriteTime:yyyy-MM-dd HH:mm}",
                Font      = Theme.Mono(9),
                ForeColor = Theme.TextDim,
                AutoSize  = true,
                Location  = new Point(16, 30),
            };
            d.Click += OnOpenFileClick;
            d.Tag    = card.Tag;
            card.Controls.Add(d);

            body.Controls.Add(card);
            y += 64;
        }
        body.Height = y + 12;

        return page;
    }

    private static string FormatFileSize(long bytes)
    {
        if (bytes < 1024)            return $"{bytes} B";
        if (bytes < 1024 * 1024)     return $"{bytes / 1024.0:F1} KB";
        if (bytes < 1024 * 1024 * 1024) return $"{bytes / (1024.0 * 1024):F1} MB";
        return $"{bytes / (1024.0 * 1024 * 1024):F2} GB";
    }

    // ============================================================================
    //  PAGE 6: CONSOLE
    // ============================================================================
    private Panel BuildConsolePage()
    {
        var page = new Panel { BackColor = Theme.Bg };
        var layout = new TableLayoutPanel
        {
            BackColor = Theme.Bg,
            Dock = DockStyle.Fill,
            ColumnCount = 1,
            RowCount = 2,
            Margin = Padding.Empty,
            Padding = Padding.Empty,
        };
        layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
        layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 90));
        layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
        page.Controls.Add(layout);

        var header = new Panel
        {
            BackColor = Theme.Bg,
            Dock = DockStyle.Fill,
            Margin = Padding.Empty,
        };
        layout.Controls.Add(header, 0, 0);

        var title = new Label
        {
            Text      = "Console Output",
            Font      = Theme.PageTitle(),
            ForeColor = Theme.Accent,
            AutoSize  = true,
            Location  = new Point(8, 8),
        };
        header.Controls.Add(title);

        var clearBtn = new Button
        {
            Text      = "Clear",
            Location  = new Point(8, 50),
            Size      = new Size(100, 30),
            FlatStyle = FlatStyle.Flat,
            BackColor = Theme.BtnHover,
            ForeColor = Theme.TextMain,
            Font      = new Font("Segoe UI", 9, FontStyle.Bold),
            Cursor    = Cursors.Hand,
        };
        clearBtn.FlatAppearance.BorderSize = 0;
        clearBtn.Click += OnClearConsoleClick;
        header.Controls.Add(clearBtn);

        var saveBtn = new Button
        {
            Text      = "Save to File",
            Location  = new Point(116, 50),
            Size      = new Size(110, 30),
            FlatStyle = FlatStyle.Flat,
            BackColor = Theme.BtnHover,
            ForeColor = Theme.TextMain,
            Font      = new Font("Segoe UI", 9, FontStyle.Bold),
            Cursor    = Cursors.Hand,
        };
        saveBtn.FlatAppearance.BorderSize = 0;
        saveBtn.Click += OnSaveConsoleClick;
        header.Controls.Add(saveBtn);

        _consoleAutoScroll.Text      = "Auto-scroll";
        _consoleAutoScroll.Location  = new Point(238, 56);
        _consoleAutoScroll.AutoSize  = true;
        _consoleAutoScroll.Checked   = true;
        _consoleAutoScroll.ForeColor = Theme.TextMain;
        _consoleAutoScroll.BackColor = Theme.Bg;
        _consoleAutoScroll.Font      = new Font("Segoe UI", 9);
        header.Controls.Add(_consoleAutoScroll);

        _consoleDroppedLabel.Location  = new Point(360, 56);
        _consoleDroppedLabel.AutoSize  = true;
        _consoleDroppedLabel.Font      = new Font("Segoe UI", 9);
        _consoleDroppedLabel.ForeColor = Theme.TextDim;
        _consoleDroppedLabel.Text      = "";
        header.Controls.Add(_consoleDroppedLabel);

        var consoleHost = new Panel
        {
            BackColor = Theme.Bg,
            Dock = DockStyle.Fill,
            Margin = Padding.Empty,
            Padding = new Padding(8, 0, 8, 0),
        };
        layout.Controls.Add(consoleHost, 0, 1);

        _consoleBox.Dock        = DockStyle.Fill;
        _consoleBox.Font        = Theme.Mono(9);
        _consoleBox.BackColor   = Theme.ConsoleBg;
        _consoleBox.ForeColor   = Theme.ConsoleText;
        _consoleBox.ReadOnly    = true;
        // Wrap long paths and alert messages. A horizontal scrollbar is
        // easy to miss in the dark theme and previously left the important
        // tail of each line visually clipped.
        _consoleBox.WordWrap    = true;
        _consoleBox.ScrollBars  = RichTextBoxScrollBars.ForcedVertical;
        _consoleBox.BorderStyle = BorderStyle.None;
        consoleHost.Controls.Add(_consoleBox);

        return page;
    }
}
